apiVersion: v1
kind: Pod
metadata:
  name: pod-with-volume
spec:
  volumes:
    - name: k8s-volume
      persistentVolumeClaim:
        claimName: myclaim
  containers:
    - name: httpd
      image: httpd:latest
      command: ["/bin/sh"]
      args: ["-c","sleep 1000"]      
      volumeMounts:
      - name: k8s-volume
        mountPath: /conf
