apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0011
  labels:
    type: local 
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes: [ "ReadWriteOnce" ] 
  hostPath:
    path: "/kube"
